name: passman
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1-beta

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  at_client_mobile: ^3.1.14
  at_onboarding_flutter: ^4.0.2
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.5.3+1
  flutter_qr_reader: ^1.0.5
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  local_auth: ^2.0.2
  lottie: ^1.3.0
  package_info_plus: ^1.4.2
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  provider: ^6.0.2
  secure_application: ^3.8.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  tabler_icons: ^0.0.3
  uuid: ^3.0.6

dependency_overrides:
  at_client: ^3.0.23
  test: ^1.21.1
  test_api: ^0.4.9
# at_lookup: ^3.0.14
# at_commons: ^3.0.13
# git:
#   url: https://github.com/atsign-foundation/at_client_sdk.git
#   ref: trunk
#   path: at_client
dev_dependencies:
  build_runner: ^2.1.10
  lints: ^1.0.1
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/images/
    - assets/images/cards/
    - assets/lottie/
    - assets/config/

flutter_icons:
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFFFF"
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/android_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

import_sorter:
  emojis: true
