name: passman
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1-beta.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  at_client_mobile: ^3.1.13
  at_onboarding_flutter: ^4.0.1
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  local_auth: ^1.1.11
  lottie: ^1.2.2
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  provider: ^6.0.2
  qr_code_scanner: ^0.7.0
  secure_application: ^3.8.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  tabler_icons: ^0.0.3
  uuid: ^3.0.6
  permission_handler: ^9.2.0

dependency_overrides:
  at_lookup: ^3.0.14
  at_commons: ^3.0.13
  
dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  import_sorter: ^4.6.0
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/images/
    - assets/images/cards/
    - assets/lottie/
    - assets/config/

flutter_icons:
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFFFF"
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/android_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

import_sorter:
  emojis: true
